using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;


namespace SIL.Transcriber.Models
{

    public class NewTask
    {
        public string taskID { get; set; }
        public string name { get; set; }
        public string passageSet { get; set; }
        public string book { get; set; }
        public string description { get; set; }
        //public List<Media> audio { get; set; }
    }
    public class TransTask
    {
        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId _id { get; set; }
        public string taskID { get; set; }
        public string name { get; set; }
        public string passageSet { get; set; }
        public string book { get; set; }
        public string description { get; set; }
        //public List<Media> audio { get; set; }
    }
}
