using SIL.XForge.Models;

namespace SIL.Transcriber.Models
{
    public abstract class TranscriberTaskEntity : Entity
    {
        // standard BSonId generated by MongoDb
        //public string Id { get; set; }
        public string TaskID { get; set; }
        public string Name { get; set; }
        public string PassageSet { get; set; }
        public string Book { get; set; }
        public string Description { get; set; }
    }
}